version: "3.3"
services:
  nginx:
    container_name: nszl-nginx
    build: requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/var/www/html
    networks:
      - frontend
    restart: always
    
  mariadb:
    container_name: nszl-mariadb
    build: requirements/mariadb
    ports:
      - "3306"
    volumes:
      # - /home/jng/data-incep:/docker_mysqldata
      - ~/data-incep:/docker_mysqldata
    environment:
      MYSQL_ADMIN: ${MYSQL_ADMIN}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASSWORD : ${MYSQL_PASSWORD}
      WORDPRESS_DATABASE : ${WORDPRESS_DATABASE}
    networks:
      - backend
    restart :
      always

  wordpress:
    container_name: nszl-wordpress
    build: requirements/wordpress
    volumes:
      - ./static:/wp_site
    ports:
      - "9000:9000"
    networks:
      - backend
      - frontend
    restart :
      always

networks:
  frontend:
  backend: