version: "3.3"
services:
  nginx:
    container_name: nszl-nginx
    build: requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    
  mariadb:
    container_name: nszl-mariadb
    build: requirements/mariadb
    ports:
      - "3306" : "3306"
    environment:
      MYSQL_ADMIN: ${MYSQL_ADMIN}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASSWORD : ${MYSQL_PASSWORD}