version: "3.3"
services:

  mariadb:
    container_name: nszl-mariadb
    build: requirements/mariadb
    image: mariadb
    expose:
      - "3306"
    volumes:
      - data-incep:/var/lib/mysql
      # - ~/data-incep:/docker_mysqldata
    environment:
      MYSQL_ADMIN: ${MYSQL_ADMIN}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASSWORD : ${MYSQL_PASSWORD}
      WORDPRESS_DATABASE : ${WORDPRESS_DATABASE}
    networks:
      - backend
    restart : unless-stopped

  redis:
    container_name: nszl-redis
    build: requirements/redis
    image: redis
    expose: 
      - "6379"
    networks:
      - frontend
    restart : unless-stopped

  ftp:
    container_name: nszl-ftp
    build: requirements/ftp
    image: ftp
    ports: 
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - static-incep:/static
    environment:
      FTP_USR: ${FTP_USR}
      FTP_PWD: ${FTP_PWD}
    restart : unless-stopped

  adminer:
    depends_on :
      - mariadb
    container_name: nszl-adminer
    build: requirements/adminer
    image: adminer
    ports: 
      - "8088:80"
    networks:
      - backend
    restart : unless-stopped

  wordpress:
    depends_on :
      - mariadb
      - redis
    container_name: nszl-wordpress
    build: requirements/wordpress
    image: wordpress
    volumes:
      - static-incep:/wp_site
    expose :
      - "9000"
    environment:
      MYSQL_ADMIN: ${MYSQL_ADMIN}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_PASSWORD : ${MYSQL_PASSWORD}
      WORDPRESS_DATABASE : ${WORDPRESS_DATABASE}
    networks:
      - backend
      - frontend
    restart : unless-stopped

  nginx:
    depends_on:
      - wordpress
    container_name: nszl-nginx
    image: nginx
    build: requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-incep:/var/www/html
    networks:
      - frontend
    restart: unless-stopped

  python:
    container_name: nszl-python
    image :  python
    depends_on:
      - nginx
    tty: true
    stdin_open: true
    restart : unless-stopped

networks:
  frontend:
  backend:

volumes:
  data-incep:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/jng/data

  static-incep:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/jng/inception/srcs/static
        # device: ./static #wsl